### ISSUE TITLE
Error while running the tests

### ISSUE THREAD

**Issue by prasanta303** [django-admin-tools/django-admin-tools#114]
Downloaded the code, unzipped it and go to folder '**test_proj**'.
Then tried to run using command '**python manage.py test**' from DOS command line.

**Getting the error as below**,
_Traceback (most recent call last):
  File "manage.py", line 31, in <module>
    manage_16ormore()
  File "manage.py", line 16, in manage_16ormore
    execute_from_command_line(sys.argv)
................................
..................................
........................................
OSError: [Errno 22] Invalid argument: '...django-admin-tools-master\\test_proj\\templates\\admin:admin\\base.html'_

Help me in resolving the issue to run. My aim is to customize it after getting run able AS-IS.

**Comment by prasanta303** [comment]
Resolved from "**Error on windows envirament #32**"
