### ISSUE TITLE
dont work in django 4 python 3.8 -unable to import dashboard.py

### ISSUE THREAD

**Issue by Obie-Wan** [django-admin-tools/django-admin-tools#119]
`nternal Server Error: /admin/
Traceback (most recent call last):
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/base.py", line 176, in render
    return self._render(context)
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/test/utils.py", line 101, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/base.py", line 977, in render
    return SafeString(''.join([
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render_annotated
    return self.render(context)
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 153, in render
    return compiled_parent._render(context)
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/test/utils.py", line 101, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/base.py", line 977, in render
    return SafeString(''.join([
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render_annotated
    return self.render(context)
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 153, in render
    return compiled_parent._render(context)
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/test/utils.py", line 101, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/base.py", line 977, in render
    return SafeString(''.join([
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render_annotated
    return self.render(context)
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 153, in render
    return compiled_parent._render(context)
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/test/utils.py", line 101, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/base.py", line 977, in render
    return SafeString(''.join([
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render_annotated
    return self.render(context)
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 153, in render
    return compiled_parent._render(context)
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/test/utils.py", line 101, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/base.py", line 977, in render
    return SafeString(''.join([
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render_annotated
    return self.render(context)
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 153, in render
    return compiled_parent._render(context)
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/test/utils.py", line 101, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/base.py", line 977, in render
    return SafeString(''.join([
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render_annotated
    return self.render(context)
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/base.py", line 977, in render
    return SafeString(''.join([
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render_annotated
    return self.render(context)
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/base.py", line 977, in render
    return SafeString(''.join([
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render_annotated
    return self.render(context)
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/django/template/library.py", line 215, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/admin_tools/dashboard/templatetags/admin_tools_dashboard_tags.py", line 117, in admin_tools_render_dashboard_css
    dashboard = get_dashboard(context, location)
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/admin_tools/dashboard/utils.py", line 26, in get_dashboard
    return get_index_dashboard(context)
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/admin_tools/dashboard/utils.py", line 55, in get_index_dashboard
    return _get_dashboard_cls(getattr(
  File "/home/kirill/projects/sass/ma-manager-admin/venv/lib/python3.8/site-packages/admin_tools/dashboard/utils.py", line 46, in _get_dashboard_cls
    mod = import_module(mod)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'multi_manager.dashboard'`

**Comment by chayim** [comment]
Have you tried latest and latest? Running Django 4.2, and Python 3.11.3 I can't reproduce this. I have things configured accordingly:

**settings.py**
```ADMIN_TOOLS_INDEX_DASHBOARD='myapp.dashboard.CustomIndexDashboard'
```

Then in *<project root with mangage.py>/myapp/dashboard.py* I have the generated dashboard file.
